apiVersion: operator.kyma-project.io/v1alpha1
kind: KymaPolicyConfig
metadata:
  labels:
    app.kubernetes.io/name: policy-manager
    app.kubernetes.io/managed-by: kustomize
  name: kymapolicyconfig-sample
spec:
  # TODO(user): Add fields here
